export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GET_MY_INFO_SUCCESS = "GET_MY_INFO_SUCCESS";
export const GET_MY_INFO_FAIL = "GET_MY_INFO_FAIL";
export const GET_MY_INFO_REQUESTED = "GET_MY_INFO_REQUESTED";

export const LOGOUT_USER_REQUESTED = "LOGOUT_USER_REQUESTED";
